### ISSUE TITLE
[FR] Allow disabling messages/warnings when `draft` documentclass option is used

### ISSUE THREAD

**Issue by gusbrs** [FrankMittelbach/fmitex-widows-and-orphans#1]
Hi,

this is a small suggestion / feature request. It would be nice if `widows-and-orphans` were able to inhibit warnings and messages when the documentclass `draft` option is in use. This way, one could just leave the package in the preamble by default, not having to remember to include it on a final typesetting stage and, conversely, not having to worry about such messages at early stages of the document.

If you think it is a good idea, it would be much appreciated.

**Comment by FrankMittelbach** [comment]
sorry that it took me so long to get back to this. If finally made the change and honor "draft" by turning the check warnings into info messages, ie, they still appear in the .log file but not on the terminal. I just don't want to see them gone completely by default. This change will show up in a few days on CTAN and in the distributions.

**Comment by gusbrs** [comment]
Thank you!
