### ISSUE TITLE
Error with TeXlive2022

### ISSUE THREAD

**Issue by texwidowsandorphans** [FrankMittelbach/fmitex-widows-and-orphans#3]
TeXlive2022 on Linux Mint 20.3

Test document:

\documentclass[a4paper,12pt]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{lmodern}
\usepackage{microtype}

\usepackage{blindtext}

\usepackage[orphans=prevent,widows=avoid]{widows-and-orphans}

\title{}
\author{}

\begin{document}
\Blinddocument
\maketitle
\begin{abstract}
\end{abstract}
\section*{1}
\end{document}

or any other possible option of "widows-and-orphans" (with or without package "microtype") results in error message:

Datei: expl3.sty
Log: Fehler
Zeile: Zeile 77
Fehlertext: LaTeX3 Error: Mismatched LaTeX support files detected. \ExplLoaderFileDate{expl3.sty}}

**Comment by FrankMittelbach** [comment]
The latex format and the kernel support files at your installation do not match. The format needs to be regenerated if they are updated which hasn't happened for some reason. Nothing to do with this package
